version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv lock
      - pipenv install awscli
      - pipenv lock
      - pipenv install aws-sam-cli
      - pipenv lock
      - pipenv run sam package --template-file template.yml --s3-bucket serverless-reminder-app-bucket --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
