version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pip install awscli
      - pip install aws-sam-cli
      - sam package --template-file template.yml --s3-bucket serverless-reminder-app-bucket --output-template-file packaged-template.yml
      - sam deploy --template-file packaged-template.yml --stack-name serverless-reminder-app-bucket --capabilities CAPABILITY_IAM
artifacts:
  files:
    - packaged-template.yml
